# Generated by Django 2.0.7 on 2018-07-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('inventory', '0004_auto_20180710_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Deliver')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivers', models.ManyToManyField(to='delivery.Deliver')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Client')),
                ('products', models.ManyToManyField(to='inventory.Product')),
            ],
        ),
        migrations.AddField(
            model_name='deliverypackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Package'),
        ),
        migrations.AddField(
            model_name='deliver',
            name='deliveryPackages',
            field=models.ManyToManyField(to='delivery.DeliveryPackage'),
        ),
    ]
