# Generated by Django 2.0.7 on 2018-07-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20180710_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='products',
            field=models.ManyToManyField(null=True, to='inventory.Product'),
        ),
    ]
