# Generated by Django 2.0.7 on 2018-07-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20180717_1718'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliver',
            name='user',
        ),
        migrations.DeleteModel(
            name='Deliver',
        ),
        migrations.AddField(
            model_name='person',
            name='deliverInfos',
            field=models.ManyToManyField(null=True, to='user_management.DeliverInfo'),
        ),
    ]
