# Generated by Django 2.0.7 on 2018-07-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
    ]
